source 'https://rubygems.org'
ruby '2.4.1'

gem 'sinatra', '~> 2.0.0'

group :development do
  gem 'rerun', '~> 0.11.0'
end

group :test do
  gem 'rspec', '~> 3.6.0'
  gem 'rack-test', '~> 0.8.2'
end
